services:

  db:
    container_name: db_dev
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app_dev
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c "npx sequelize db:migrate && npx sequelize db:seed:all && npx nodemon src/index.js"
