FROM node:alpine

# Create app directory, where the app will be stored
WORKDIR /app 

# Copy package.json and package-lock.json to the app directory. The * is a wildcard, so it will copy both files
COPY package*.json ./

# Establecer NODE_ENV a desarrollo para incluir devDependencies
ENV NODE_ENV=development

# Install the dependencies
RUN npm install

# Copy the rest of the files to the app directory
COPY . .

# Expose the port 3000
EXPOSE 3000

CMD ["npx", "nodemon", "src/index.js"]
